### ISSUE TITLE
New User Registration Issue

### ISSUE THREAD

**Issue by clarknelson** [c10d-dev/craft-hcaptcha#1] opened 2021-10-19 15:04 UTC
Hello, thank you for your plugin :)

I am experiencing an issue with this option in the settings:
![Screenshot from 2021-10-19 09-55-33](https://user-images.githubusercontent.com/4106671/137936723-e33a9c71-342f-41f4-b434-0cf8bc397a9d.png)

I am using the standard user registration form like this: https://craftcms.com/knowledge-base/front-end-user-accounts#registration-form

When I try to verify I can successfully complete the captcha, but the user object comes back with the following error:
`Please verify you are human.`

When I unchecked the box, I can register fine. I wasn't able to find too much relevant information in the logs, but here is the session variable:
```
$_SESSION = [
    '240364006149420517839f0929062b0b__flash' => [
        'notice' => -1
        'error' => -1
    ]
    'notice' => 'User registered.'
    'error' => 'Couldn’t save user.'
]
```

**Comment by c10d-dev** [comment] 2021-10-19 23:10
Hello,
Thank you for creating an issue!

I'm sorry to see that the plugin does not work as intended.
Can you explain how did you inject the captcha render ?

The only thing you should have to add into the registration form is something like this : 
```
<label for="hcaptcha-1">hCAPTCHA</label>
{{ craft.hcaptcha.render() }}
{% if user is defined %}
  {{ _self.errorList(user.getErrors('hcaptcha')) }}
{% endif %}
```

Hope this can help!

**Comment by c10d-dev** [comment] 2021-10-20 01:17
I just pushed an update (v1.1.1) on the validation event that I think could help solve this issue.

See [24d18dd2](https://github.com/c10d-dev/craft-hcaptcha/commit/24d18dd2359734669870f56d4d405ffb51fcad78)

**Comment by clarknelson** [comment] 2021-10-20 01:28
Great thank you! Same message though :)

I see a console message now for the hcaptcha script `recaptchacompat disabled` maybe that is helpful? I am including the form just like `{{ craft.hcaptcha.render() }}`

Edit: no rush, I have found another solution, but I am willing to help you resolve. I remember this working a few weeks ago

**Comment by c10d-dev** [comment] 2021-10-21 01:46
All right!

Which version of Craft CMS are you using?
Could you also list all the plugins enabled?

Thanks

**Comment by c10d-dev** [comment] 2021-11-06 14:40
Closing this issue due to the lack of informations.
Feel free to reopen it if you want to provide more context!

**Closed as completed by c10d-dev** 2021-11-06 14:40 UTC
